// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDownload(arg1) {
  return window['go']['main']['App']['AddDownload'](arg1);
}

export function ChooseFolder(arg1) {
  return window['go']['main']['App']['ChooseFolder'](arg1);
}

export function FrontendReady() {
  return window['go']['main']['App']['FrontendReady']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetIntegration() {
  return window['go']['main']['App']['GetIntegration']();
}

export function InstallIntegration() {
  return window['go']['main']['App']['InstallIntegration']();
}

export function ListDownloads() {
  return window['go']['main']['App']['ListDownloads']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function PauseAll() {
  return window['go']['main']['App']['PauseAll']();
}

export function PauseDownload(arg1) {
  return window['go']['main']['App']['PauseDownload'](arg1);
}

export function ProbeURL(arg1, arg2) {
  return window['go']['main']['App']['ProbeURL'](arg1, arg2);
}

export function RemoveDownload(arg1, arg2) {
  return window['go']['main']['App']['RemoveDownload'](arg1, arg2);
}

export function RemoveIntegration() {
  return window['go']['main']['App']['RemoveIntegration']();
}

export function ResumeAll() {
  return window['go']['main']['App']['ResumeAll']();
}

export function ResumeDownload(arg1) {
  return window['go']['main']['App']['ResumeDownload'](arg1);
}

export function RevealExtensionFolder() {
  return window['go']['main']['App']['RevealExtensionFolder']();
}

export function RevealFirefoxExtension() {
  return window['go']['main']['App']['RevealFirefoxExtension']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function ShowInFolder(arg1) {
  return window['go']['main']['App']['ShowInFolder'](arg1);
}
