// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {engine} from '../models';

export function AddDownload(arg1:engine.AddRequest):Promise<engine.Info>;

export function ChooseFolder(arg1:string):Promise<string>;

export function GetConfig():Promise<engine.Config>;

export function ListDownloads():Promise<Array<engine.Info>>;

export function OpenFile(arg1:string):Promise<void>;

export function PauseAll():Promise<void>;

export function PauseDownload(arg1:string):Promise<void>;

export function ProbeURL(arg1:string):Promise<engine.ProbeResult>;

export function RemoveDownload(arg1:string,arg2:boolean):Promise<void>;

export function ResumeAll():Promise<void>;

export function ResumeDownload(arg1:string):Promise<void>;

export function SaveConfig(arg1:engine.Config):Promise<engine.Config>;

export function ShowInFolder(arg1:string):Promise<void>;
